import { View, Text, StyleSheet, ScrollView } from "react-native";

export default function PrivacyModal() {
  return (
    <View style={styles.modalContainer}>
      <Text style={styles.title}>Privacy Policy</Text>
      <ScrollView>
        <Text style={styles.sectionTitle}>0. Definitions</Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>0.1</Text> “
          <Text style={styles.bold}>Application</Text>” refers to this mobile
          software, its services, and associated content.{"\n"}
          <Text style={styles.underline}>0.2</Text> “
          <Text style={styles.bold}>We</Text>,” “
          <Text style={styles.bold}>Us</Text>,” or “
          <Text style={styles.bold}>Our</Text>” refers to the developer and
          legal owner of the Application.{"\n"}
          <Text style={styles.underline}>0.3</Text> “
          <Text style={styles.bold}>You</Text>” or “
          <Text style={styles.bold}>User</Text>” refers to the individual who
          accesses or uses the Application.{"\n"}
          <Text style={styles.underline}>0.4</Text> “
          <Text style={styles.bold}>Recipe(s)</Text>” refers to any cooking
          instructions, ingredient lists, or related suggestions generated by
          any AI model our Application’s uses.
        </Text>

        <Text style={styles.sectionTitle}>1. Information We Collect</Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>1.1</Text>{" "}
          <Text style={styles.bold}>Account Information:</Text> When you sign in
          using Google or Apple (via Firebase Authentication), we collect and
          store your generated user ID, name, and email address.{"\n"}
          <Text style={styles.underline}>1.2</Text>{" "}
          <Text style={styles.bold}>Photo Data:</Text> We may collect and store
          any images you upload, together with metadata such as timestamp, file
          size, and device type.
        </Text>

        <Text style={styles.sectionTitle}>2. Purpose of Data Processing</Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>2.1</Text>{" "}
          <Text style={styles.bold}>
            Authentication and Account Maintenance:
          </Text>{" "}
          To provide secure sign-in and account management via Firebase.{"\n"}
          <Text style={styles.underline}>2.2</Text>{" "}
          <Text style={styles.bold}>Recipe Generation:</Text> To process
          uploaded images through OpenRouter’s AI models for item identification
          and recipe generation. Recipes and related metadata are stored locally
          on your device.
        </Text>

        <Text style={styles.sectionTitle}>
          3. Data Sharing and Third Parties
        </Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>3.1</Text>{" "}
          <Text style={styles.bold}>Firebase (Google LLC):</Text> Provides
          authentication services.{"\n"}
          <Text style={styles.underline}>3.2</Text>{" "}
          <Text style={styles.bold}>OpenRouter AI Services:</Text> Processes
          your uploaded images for recipe generation.{"\n"}
          <Text style={styles.underline}>3.3</Text> We will{" "}
          <Text style={styles.bold}>never</Text> sell, lease, or otherwise
          distribute your personal information to third parties for any
          purposes.
          <Text style={styles.sectionTitle}>
            3. Data Sharing and Third Parties
          </Text>
          <Text style={styles.text}>
            <Text style={styles.underline}>3.1</Text>{" "}
            <Text style={styles.bold}>Firebase (Google LLC):</Text> Provides
            authentication services.{"\n"}
            <Text style={styles.underline}>3.2</Text>{" "}
            <Text style={styles.bold}>OpenRouter AI Services:</Text> Processes
            your uploaded images for recipe generation.{"\n"}
            <Text style={styles.underline}>3.3</Text> We do{" "}
            <Text style={styles.bold}>not</Text> sell, lease, or otherwise
            distribute your personal information to any third party. We also do{" "}
            <Text style={styles.bold}>not</Text> use your data for any
            first-party marketing, targeted content, algorithmic
            recommendations, personalization, analytics, or any purpose beyond
            what is strictly necessary to operate and maintain the core
            functionality of the Application. Your data is stored solely for
            functionality and is not otherwise processed, analyzed, or utilized
            by Us.
          </Text>
        </Text>

        <Text style={styles.sectionTitle}>
          4. Disclaimer of Warranties and Limitation of Liability
        </Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>4.1</Text> All recipes generated
          through the Application are provided “as is” for informational
          purposes only.{"\n"}
          <Text style={styles.underline}>4.2</Text> We make no representation or
          warranty, express or implied, regarding the accuracy, completeness,
          safety, or suitability of any recipe or cooking method.{"\n"}
          <Text style={styles.underline}>4.3</Text> You acknowledge and agree
          that food preparation carries inherent risks, including but not
          limited to foodborne illness, allergic reactions, and physical injury.
          {"\n"}
          <Text style={styles.underline}>4.4</Text> Under no circumstances shall
          We be liable for any injury, illness, loss, damage, or expense arising
          from (a) reliance on any recipe or suggestion provided by the AI
          model; (b) improper food handling or preparation; or (c) failure to
          follow applicable food safety guidelines.{"\n"}
          <Text style={styles.underline}>4.5</Text> By using this Application,
          You expressly assume all associated risks and release Us from any
          liability, to the fullest extent permitted by law.
        </Text>

        <Text style={styles.sectionTitle}>5. Amendments to This Policy</Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>5.1</Text> We reserve the right to
          amend this Privacy Policy at any time, with or without prior notice.
          {"\n"}
          <Text style={styles.underline}>5.2</Text> Your continued use of the
          Application following any amendment constitutes acceptance of the
          revised terms.
        </Text>

        <Text style={styles.sectionTitle}>6. Contact Information</Text>
        <Text style={styles.text}>
          If you have any questions regarding this Privacy Policy or the
          handling of your data, you may contact the developer at:
          badhrihari123@gmail.com
        </Text>

        <Text style={styles.sectionTitle}>7. Acknowledgment and Consent</Text>
        <Text style={styles.text}>
          By accessing or using this Application, You acknowledge that You have
          read, understood, and agreed to be bound by this Privacy Policy,
          including the Disclaimer and Limitation of Liability provisions.
        </Text>

        <Text style={styles.sectionTitle}>8. Data Retention</Text>
        <Text style={styles.text}>
          <Text style={styles.underline}>8.1</Text> You may request the deletion
          of your account and all associated data at any time by contacting Us
          at the email address provided in Section 6. Upon verification of your
          request, We will permanently erase the data from Our active systems
          and backups to the extent technically feasible.{"\n"}
          <Text style={styles.underline}>8.2</Text> We do not maintain
          indefinite archives of user data and do not store data for potential
          future use or analysis.
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: "#000",
    padding: 20,
  },
  title: {
    fontSize: 24,
    color: "#fff",
    marginBottom: 12,
    fontWeight: "600",
  },
  sectionTitle: {
    fontSize: 16,
    color: "#fff",
    marginTop: 12,
    marginBottom: 4,
    fontWeight: "500",
  },
  underline: {
    textDecorationLine: "underline",
    fontWeight: "700",
    color: "#fff",
  },
  text: {
    color: "#fff",
    lineHeight: 20,
  },
  bold: {
    fontWeight: "700",
  },
});
